services:
  mineotter:
    image: mineotter:latest
    container_name: bot_discord-mineotter
    restart: unless-stopped
    ports:
      - "9503:3000"
    env_file:
      - .env
    environment:
      DOCKER_HOST: tcp://docker_proxy-discord_bots:2375
    volumes:
      - ./channels.json:/app/channels.json
      - ./cache:/app/cache
    networks:
      - mineotter_bridge
      - discord-bots-net
      - games-net
      - pocketbase_network

networks:
  mineotter_bridge:
    driver: bridge
  discord-bots-net:
    name: discord-bots-net
    external: true
  games-net:
    name: server-net
    external: true
  pocketbase_network:
    name: pocketbase_network
    external: true