services:
  mateloutre:
    image: mateloutre:latest
    container_name: bot_discord-mateloutre
    restart: unless-stopped
    ports:
      - "9502:3000"
    env_file:
      - .env
    volumes:
      - ./channels.json:/app/channels.json
      - ./cache:/app/cache
    networks:
      - mateloutre_bridge
      - discord-bots-net
      - pocketbase_network

networks:
  mateloutre_bridge:
    driver: bridge
  discord-bots-net:
    name: discord-bots-net
    external: true
  pocketbase_network:
    name: pocketbase_network
    external: true